import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import { CountButton } from "../components/Container/CounterButton";
import { CounterButton } from "../components/CounterButton";

const H1 = styled.h1`
  color: red;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CountButton label="label" maximum={100} />
        <CounterButton label="Counter Button Label." maximum={100} />
        <div className={styles.container}>
          <main className={styles.main}>
            <H1>
              Welcome to <a href="https://nextjs.org">Next.js</a>
            </H1>
          </main>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
